begin;

create extension if not exists pgtap with schema extensions;

select no_plan();

-- Catalog shape, constraints, ownership, and the explicit RPC-only boundary.
select has_table(
  'public',
  'user_notifications',
  'user_notifications is an application table in the public schema'
);

select is(
  (
    select pg_catalog.array_agg(
      column_name || ':' || data_type
      order by ordinal_position
    )
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'user_notifications'
  ),
  array[
    'id:uuid',
    'recipient_id:uuid',
    'actor_id:uuid',
    'notification_type:text',
    'relationship_low_id:uuid',
    'relationship_high_id:uuid',
    'relationship_version:bigint',
    'created_at:timestamp with time zone',
    'expires_at:timestamp with time zone',
    'read_at:timestamp with time zone',
    'suppressed_at:timestamp with time zone'
  ],
  'notification columns contain only the accepted reference and lifecycle data'
);

select is(
  (
    select pg_catalog.array_agg(column_name order by ordinal_position)
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'user_notifications'
      and is_nullable = 'YES'
  ),
  array['read_at', 'suppressed_at']::information_schema.sql_identifier[],
  'only read and suppression timestamps are nullable'
);

select is(
  (
    select column_default::text
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'user_notifications'
      and column_name = 'id'
  ),
  'gen_random_uuid()'::text,
  'notification IDs are generated by the database'
);

select ok(
  (
    select column_default = 'now()'
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'user_notifications'
      and column_name = 'created_at'
  )
  and (
    select column_default like '%180 days%'
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'user_notifications'
      and column_name = 'expires_at'
  ),
  'creation and exact logical expiry are database-managed defaults'
);

select is(
  (
    select pg_catalog.array_agg(conname order by conname)
    from pg_catalog.pg_constraint
    where conrelid = 'public.user_notifications'::regclass
      and contype = 'c'
  ),
  array[
    'user_notifications_distinct_participants_check',
    'user_notifications_exact_expiry_check',
    'user_notifications_ordered_pair_check',
    'user_notifications_pair_participants_check',
    'user_notifications_positive_version_check',
    'user_notifications_read_time_check',
    'user_notifications_suppression_time_check',
    'user_notifications_type_check'
  ]::name[],
  'every notification invariant has a named check constraint'
);

select is(
  (
    select count(*)
    from pg_catalog.pg_constraint
    where conrelid = 'public.user_notifications'::regclass
      and contype = 'f'
      and confdeltype = 'a'
  ),
  3::bigint,
  'all profile and relationship foreign keys are non-cascading'
);

select is(
  (
    select pg_catalog.array_agg(
      attribute.attname
      order by key_column.ordinality
    )
    from pg_catalog.pg_constraint as constraint_record
    cross join lateral pg_catalog.unnest(constraint_record.conkey)
      with ordinality as key_column(attribute_number, ordinality)
    join pg_catalog.pg_attribute as attribute
      on attribute.attrelid = constraint_record.conrelid
      and attribute.attnum = key_column.attribute_number
    where constraint_record.conrelid = 'public.user_notifications'::regclass
      and constraint_record.conname = 'user_notifications_pair_version_key'
  ),
  array[
    'relationship_low_id',
    'relationship_high_id',
    'recipient_id',
    'notification_type',
    'relationship_version'
  ]::name[],
  'the uniqueness boundary prevents duplicate pair-version notifications'
);

select is(
  (
    select pg_catalog.array_agg(indexname order by indexname)
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and tablename = 'user_notifications'
  ),
  array[
    'user_notifications_pair_version_key',
    'user_notifications_pkey',
    'user_notifications_recipient_unread_expiry_idx',
    'user_notifications_recipient_visible_created_idx'
  ]::name[],
  'only required identity, uniqueness, listing, and badge indexes exist'
);

select ok(
  (
    select indexdef like '%(recipient_id, created_at DESC, id DESC)%'
      and indexdef like '%suppressed_at IS NULL%'
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'user_notifications_recipient_visible_created_idx'
  )
  and (
    select indexdef like '%(recipient_id, expires_at)%'
      and indexdef like '%read_at IS NULL%'
      and indexdef like '%suppressed_at IS NULL%'
    from pg_catalog.pg_indexes
    where schemaname = 'public'
      and indexname = 'user_notifications_recipient_unread_expiry_idx'
  ),
  'recipient indexes match listing and unread-count access patterns'
);

select ok(
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.user_notifications'::regclass
  ),
  'user_notifications has RLS enabled'
);

select is(
  (
    select count(*)
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'user_notifications'
  ),
  1::bigint,
  'the RPC-only notification table has exactly one policy'
);

select ok(
  exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'user_notifications'
      and policyname = 'user_notifications_reject_direct_client_access'
      and cmd = 'ALL'
      and permissive = 'RESTRICTIVE'
      and roles = array['anon', 'authenticated']::name[]
      and qual = 'false'
      and with_check = 'false'
  ),
  'the restrictive policy explicitly rejects every direct client operation'
);

select ok(
  not has_table_privilege('anon', 'public.user_notifications', 'SELECT')
  and not has_table_privilege('anon', 'public.user_notifications', 'INSERT')
  and not has_table_privilege('anon', 'public.user_notifications', 'UPDATE')
  and not has_table_privilege('anon', 'public.user_notifications', 'DELETE')
  and not has_table_privilege('authenticated', 'public.user_notifications', 'SELECT')
  and not has_table_privilege('authenticated', 'public.user_notifications', 'INSERT')
  and not has_table_privilege('authenticated', 'public.user_notifications', 'UPDATE')
  and not has_table_privilege('authenticated', 'public.user_notifications', 'DELETE')
  and not has_table_privilege('service_role', 'public.user_notifications', 'SELECT')
  and not has_table_privilege('service_role', 'public.user_notifications', 'INSERT')
  and not has_table_privilege('service_role', 'public.user_notifications', 'UPDATE')
  and not has_table_privilege('service_role', 'public.user_notifications', 'DELETE'),
  'no Data API client role has direct notification table privileges'
);

select is(
  pg_catalog.pg_get_userbyid(
    (select relowner from pg_catalog.pg_class where oid = 'public.user_notifications'::regclass)
  ),
  'postgres',
  'PostgreSQL owns the notification table'
);

select is(
  pg_catalog.obj_description('public.user_notifications'::regclass, 'pg_class'),
  'RPC-only persistent in-app notifications; initially friend requests only.',
  'the notification table has a stable security-boundary comment'
);

select is(
  (
    select count(*)
    from pg_catalog.pg_proc
    where oid in (
      'public.list_notifications(integer,timestamptz,uuid)'::regprocedure,
      'public.get_unread_notification_count()'::regprocedure,
      'public.mark_notifications_read(uuid[])'::regprocedure
    )
  ),
  3::bigint,
  'all three exact authenticated notification RPC signatures exist'
);

select is(
  (
    select count(*)
    from pg_catalog.pg_proc
    where oid in (
      'public.list_notifications(integer,timestamptz,uuid)'::regprocedure,
      'public.get_unread_notification_count()'::regprocedure,
      'public.mark_notifications_read(uuid[])'::regprocedure
    )
      and prosecdef
      and proconfig @> array['search_path=""']
      and pg_catalog.pg_get_userbyid(proowner) = 'postgres'
  ),
  3::bigint,
  'every notification RPC is PostgreSQL-owned and pins an empty definer search path'
);

select ok(
  (
    select provolatile = 's'
    from pg_catalog.pg_proc
    where oid = 'public.list_notifications(integer,timestamptz,uuid)'::regprocedure
  )
  and (
    select provolatile = 's'
    from pg_catalog.pg_proc
    where oid = 'public.get_unread_notification_count()'::regprocedure
  )
  and (
    select provolatile = 'v'
    from pg_catalog.pg_proc
    where oid = 'public.mark_notifications_read(uuid[])'::regprocedure
  ),
  'read RPCs are stable and mark-read is volatile'
);

select is(
  pg_catalog.pg_get_function_result(
    'public.list_notifications(integer,timestamptz,uuid)'::regprocedure
  ),
  'TABLE(notification_id uuid, notification_type text, created_at timestamp with time zone, is_read boolean, actor_profile_id uuid, actor_username text, actor_display_name text, action_status text, expected_relationship_version bigint)'::text,
  'listing returns only the minimal Flutter projection and cursor fields'
);

select ok(
  pg_catalog.pg_get_function_result(
    'public.get_unread_notification_count()'::regprocedure
  ) = 'bigint'
  and pg_catalog.pg_get_function_result(
    'public.mark_notifications_read(uuid[])'::regprocedure
  ) = 'void',
  'count and mark-read return only the minimal results'
);

select ok(
  has_function_privilege(
    'authenticated',
    'public.list_notifications(integer,timestamptz,uuid)',
    'EXECUTE'
  )
  and has_function_privilege(
    'authenticated',
    'public.get_unread_notification_count()',
    'EXECUTE'
  )
  and has_function_privilege(
    'authenticated',
    'public.mark_notifications_read(uuid[])',
    'EXECUTE'
  ),
  'authenticated receives exactly the three notification RPCs'
);

select ok(
  not has_function_privilege(
    'anon',
    'public.list_notifications(integer,timestamptz,uuid)',
    'EXECUTE'
  )
  and not has_function_privilege(
    'anon',
    'public.get_unread_notification_count()',
    'EXECUTE'
  )
  and not has_function_privilege(
    'anon',
    'public.mark_notifications_read(uuid[])',
    'EXECUTE'
  )
  and not has_function_privilege(
    'service_role',
    'public.list_notifications(integer,timestamptz,uuid)',
    'EXECUTE'
  ),
  'anonymous and service roles cannot execute notification RPCs'
);

select ok(
  not exists (
    select 1
    from pg_catalog.pg_proc as procedure_record
    cross join lateral pg_catalog.aclexplode(procedure_record.proacl)
      as privilege_record
    where procedure_record.oid in (
      'public.list_notifications(integer,timestamptz,uuid)'::regprocedure,
      'public.get_unread_notification_count()'::regprocedure,
      'public.mark_notifications_read(uuid[])'::regprocedure
    )
      and privilege_record.grantee = 0
  ),
  'PUBLIC has no notification function execution privilege'
);

select ok(
  pg_catalog.obj_description(
    'public.list_notifications(integer,timestamptz,uuid)'::regprocedure,
    'pg_proc'
  ) is not null
  and pg_catalog.obj_description(
    'public.get_unread_notification_count()'::regprocedure,
    'pg_proc'
  ) is not null
  and pg_catalog.obj_description(
    'public.mark_notifications_read(uuid[])'::regprocedure,
    'pg_proc'
  ) is not null,
  'all notification RPCs have stable catalog comments'
);

select ok(
  pg_catalog.pg_get_userbyid(
    (select proowner from pg_catalog.pg_proc where oid = 'public.send_friend_request(uuid,bigint)'::regprocedure)
  ) = 'postgres'
  and pg_catalog.pg_get_userbyid(
    (select proowner from pg_catalog.pg_proc where oid = 'public.block_profile(uuid)'::regprocedure)
  ) = 'postgres'
  and (
    select proconfig @> array['search_path=""'] and provolatile = 'v'
    from pg_catalog.pg_proc
    where oid = 'public.send_friend_request(uuid,bigint)'::regprocedure
  )
  and (
    select proconfig @> array['search_path=""'] and provolatile = 'v'
    from pg_catalog.pg_proc
    where oid = 'public.block_profile(uuid)'::regprocedure
  ),
  'the replaced send and block functions preserve ownership, volatility, and hardening'
);

select ok(
  pg_catalog.obj_description(
    'public.send_friend_request(uuid,bigint)'::regprocedure,
    'pg_proc'
  ) = 'Creates, retries, crosses, or eligibly reopens a versioned friend request.'
  and pg_catalog.obj_description(
    'public.block_profile(uuid)'::regprocedure,
    'pg_proc'
  ) = 'Idempotently creates the caller''s outgoing block and atomically deactivates an active relationship.',
  'the replaced send and block functions preserve their reviewed comments'
);

-- Verified/onboarded, verified/incomplete, and unverified fixtures.
insert into auth.users (
  id,
  email,
  email_confirmed_at,
  created_at,
  updated_at
)
values
  ('11111111-1111-4111-8111-111111111111', 'alpha@example.test', now(), now(), now()),
  ('22222222-2222-4222-8222-222222222222', 'beta@example.test', now(), now(), now()),
  ('33333333-3333-4333-8333-333333333333', 'gamma@example.test', now(), now(), now()),
  ('44444444-4444-4444-8444-444444444444', 'delta@example.test', now(), now(), now()),
  ('55555555-5555-4555-8555-555555555555', 'epsilon@example.test', now(), now(), now()),
  ('66666666-6666-4666-8666-666666666666', 'zeta@example.test', now(), now(), now()),
  ('77777777-7777-4777-8777-777777777777', 'eta@example.test', now(), now(), now()),
  ('88888888-8888-4888-8888-888888888888', 'theta@example.test', now(), now(), now()),
  ('99999999-9999-4999-8999-999999999999', 'unverified@example.test', null, now(), now()),
  ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', 'incomplete@example.test', now(), now(), now());

update public.profiles
set username = case id
      when '11111111-1111-4111-8111-111111111111' then 'alpha_user'
      when '22222222-2222-4222-8222-222222222222' then 'beta_user'
      when '33333333-3333-4333-8333-333333333333' then 'gamma_user'
      when '44444444-4444-4444-8444-444444444444' then 'delta_user'
      when '55555555-5555-4555-8555-555555555555' then 'epsilon_user'
      when '66666666-6666-4666-8666-666666666666' then 'zeta_user'
      when '77777777-7777-4777-8777-777777777777' then 'eta_user'
      when '88888888-8888-4888-8888-888888888888' then 'theta_user'
      when '99999999-9999-4999-8999-999999999999' then 'unverified_user'
    end,
    display_name = case id
      when '11111111-1111-4111-8111-111111111111' then 'Alpha User'
      when '22222222-2222-4222-8222-222222222222' then 'Beta User'
      when '33333333-3333-4333-8333-333333333333' then 'Gamma User'
      when '44444444-4444-4444-8444-444444444444' then 'Delta User'
      when '55555555-5555-4555-8555-555555555555' then 'Epsilon User'
      when '66666666-6666-4666-8666-666666666666' then 'Zeta User'
      when '77777777-7777-4777-8777-777777777777' then 'Eta User'
      when '88888888-8888-4888-8888-888888888888' then 'Theta User'
      when '99999999-9999-4999-8999-999999999999' then 'Unverified User'
    end
where id <> 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';

-- Direct table CRUD and RPC execution remain denied outside eligible callers.
set local role anon;

select throws_like(
  $$select * from public.user_notifications$$,
  '%permission denied%user_notifications%',
  'anonymous clients cannot select notification rows directly'
);

select throws_like(
  $$insert into public.user_notifications default values$$,
  '%permission denied%user_notifications%',
  'anonymous clients cannot insert notification rows directly'
);

select throws_like(
  $$update public.user_notifications set read_at = null$$,
  '%permission denied%user_notifications%',
  'anonymous clients cannot update notification rows directly'
);

select throws_like(
  $$delete from public.user_notifications$$,
  '%permission denied%user_notifications%',
  'anonymous clients cannot delete notification rows directly'
);

select throws_like(
  $$select * from public.list_notifications(20, null, null)$$,
  '%permission denied%function%list_notifications%',
  'anonymous clients cannot list notifications'
);

select throws_like(
  $$select public.get_unread_notification_count()$$,
  '%permission denied%function%get_unread_notification_count%',
  'anonymous clients cannot read badge counts'
);

select throws_like(
  $$select public.mark_notifications_read(array[]::uuid[])$$,
  '%permission denied%function%mark_notifications_read%',
  'anonymous clients cannot mark notifications read'
);

reset role;
set local role authenticated;
set local "request.jwt.claim.sub" = '';

select throws_like(
  $$select * from public.list_notifications(20, null, null)$$,
  '%verified profile required%',
  'an authenticated role without an identity cannot list notifications'
);

select throws_like(
  $$select public.get_unread_notification_count()$$,
  '%verified profile required%',
  'an authenticated role without an identity cannot read the badge'
);

select throws_like(
  $$select public.mark_notifications_read(array[]::uuid[])$$,
  '%verified profile required%',
  'an authenticated role without an identity cannot mark notifications read'
);

set local "request.jwt.claim.sub" = '99999999-9999-4999-8999-999999999999';

select throws_like(
  $$select * from public.list_notifications(20, null, null)$$,
  '%verified profile required%',
  'an unverified caller cannot list notifications'
);

set local "request.jwt.claim.sub" = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';

select throws_like(
  $$select public.get_unread_notification_count()$$,
  '%verified profile required%',
  'a verified incomplete caller cannot read notification counts'
);

reset role;

select is(
  (select count(*) from public.user_notifications),
  0::bigint,
  'the migration does not backfill existing relationship history'
);

-- Real sends create once; duplicates and crossed sends do not.
set local role authenticated;
set local "request.jwt.claim.sub" = '11111111-1111-4111-8111-111111111111';

select lives_ok(
  $$select public.send_friend_request('22222222-2222-4222-8222-222222222222', null)$$,
  'a real first send creates relationship and notification atomically'
);

reset role;

select ok(
  (
    select recipient_id = '22222222-2222-4222-8222-222222222222'
      and actor_id = '11111111-1111-4111-8111-111111111111'
      and notification_type = 'friend_request'
      and relationship_low_id = '11111111-1111-4111-8111-111111111111'
      and relationship_high_id = '22222222-2222-4222-8222-222222222222'
      and relationship_version = 1
      and expires_at = created_at + interval '180 days'
      and read_at is null
      and suppressed_at is null
    from public.user_notifications
  ),
  'a first-send notification contains only the exact pair/version lifecycle data'
);

set local role authenticated;
set local "request.jwt.claim.sub" = '22222222-2222-4222-8222-222222222222';

select is(
  public.get_unread_notification_count(),
  1::bigint,
  'the recipient badge counts the new unread notification'
);

select ok(
  (
    select notification_type = 'friend_request'
      and not is_read
      and actor_profile_id = '11111111-1111-4111-8111-111111111111'
      and actor_username = 'alpha_user'
      and actor_display_name = 'Alpha User'
      and action_status = 'actionable'
      and expected_relationship_version = 1
    from public.list_notifications(20, null, null)
  ),
  'listing returns the minimal actionable actor projection and exact version'
);

set local "request.jwt.claim.sub" = '11111111-1111-4111-8111-111111111111';

select is(
  public.get_unread_notification_count(),
  0::bigint,
  'the actor cannot count the recipient notification'
);

select is(
  (select count(*) from public.list_notifications(20, null, null)),
  0::bigint,
  'the actor cannot list the recipient notification'
);

select lives_ok(
  $$select public.send_friend_request('22222222-2222-4222-8222-222222222222', null)$$,
  'a same-requester duplicate send remains a safe no-op'
);

reset role;

create temporary table first_notification_snapshot as
select id, created_at
from public.user_notifications;

select ok(
  (select count(*) = 1 from public.user_notifications)
  and (
    select current_row.id = snapshot.id
      and current_row.created_at = snapshot.created_at
    from public.user_notifications as current_row
    cross join first_notification_snapshot as snapshot
  ),
  'a duplicate send creates no second notification and rewrites no timestamp'
);

set local role authenticated;
set local "request.jwt.claim.sub" = '22222222-2222-4222-8222-222222222222';

select lives_ok(
  $$select public.send_friend_request('11111111-1111-4111-8111-111111111111', null)$$,
  'an opposite crossed send still becomes friendship'
);

reset role;

select ok(
  (select count(*) = 1 from public.user_notifications)
  and (
    select state = 'friends' and version = 2
    from public.user_relationships
    where profile_low_id = '11111111-1111-4111-8111-111111111111'
      and profile_high_id = '22222222-2222-4222-8222-222222222222'
  ),
  'a crossed send creates no additional notification'
);

set local role authenticated;
set local "request.jwt.claim.sub" = '22222222-2222-4222-8222-222222222222';

select ok(
  (
    select action_status = 'friends'
      and expected_relationship_version is null
    from public.list_notifications(20, null, null)
  ),
  'the original notification projects friendship without an action version'
);

select lives_ok(
  $$select public.end_friendship('11111111-1111-4111-8111-111111111111', 2)$$,
  'the existing end-friendship RPC remains valid'
);

select lives_ok(
  $$select public.send_friend_request('11111111-1111-4111-8111-111111111111', 3)$$,
  'an eligible dormant reopening creates a new pending version'
);

reset role;

select ok(
  (
    select count(*) = 1
    from public.user_notifications
    where recipient_id = '11111111-1111-4111-8111-111111111111'
      and actor_id = '22222222-2222-4222-8222-222222222222'
      and relationship_version = 4
  )
  and (select count(*) = 2 from public.user_notifications),
  'a dormant reopening creates exactly one notification for its new version'
);

set local role authenticated;
set local "request.jwt.claim.sub" = '22222222-2222-4222-8222-222222222222';

select lives_ok(
  $$select public.send_friend_request('11111111-1111-4111-8111-111111111111', 3)$$,
  'a reopened-send retry accepts the prior dormant version'
);

reset role;

select is(
  (select count(*) from public.user_notifications),
  2::bigint,
  'a reopened-send retry remains notification-idempotent'
);

-- Accepted and declined actions continue to use the authoritative relationship.
set local role authenticated;
set local "request.jwt.claim.sub" = '11111111-1111-4111-8111-111111111111';

select lives_ok(
  $$select public.send_friend_request('33333333-3333-4333-8333-333333333333', null)$$,
  'a second pair receives a first-send notification'
);

set local "request.jwt.claim.sub" = '33333333-3333-4333-8333-333333333333';

select lives_ok(
  $$select public.decline_friend_request('11111111-1111-4111-8111-111111111111', 1)$$,
  'the recipient can decline through the existing versioned RPC'
);

select ok(
  (
    select action_status = 'unavailable'
      and expected_relationship_version is null
    from public.list_notifications(20, null, null)
  ),
  'a declined notification becomes generically unavailable'
);

select lives_ok(
  $$select public.send_friend_request('11111111-1111-4111-8111-111111111111', 2)$$,
  'the eligible decliner can reopen the dormant relationship'
);

reset role;

select ok(
  exists (
    select 1
    from public.user_notifications
    where recipient_id = '11111111-1111-4111-8111-111111111111'
      and actor_id = '33333333-3333-4333-8333-333333333333'
      and relationship_version = 3
  ),
  'decliner reopening creates the new recipient/version notification'
);

set local role authenticated;
set local "request.jwt.claim.sub" = '11111111-1111-4111-8111-111111111111';

select lives_ok(
  $$select public.send_friend_request('44444444-4444-4444-8444-444444444444', null)$$,
  'an accept scenario creates one pending notification'
);

set local "request.jwt.claim.sub" = '44444444-4444-4444-8444-444444444444';

select lives_ok(
  $$select public.accept_friend_request('11111111-1111-4111-8111-111111111111', 1)$$,
  'the recipient can accept through the existing versioned RPC'
);

select ok(
  (
    select action_status = 'friends'
      and expected_relationship_version is null
    from public.list_notifications(20, null, null)
  ),
  'an accepted notification becomes a non-actionable friendship projection'
);

reset role;

select throws_like(
  $$
    insert into public.user_notifications (
      recipient_id,
      actor_id,
      notification_type,
      relationship_low_id,
      relationship_high_id,
      relationship_version
    ) values (
      '44444444-4444-4444-8444-444444444444',
      '11111111-1111-4111-8111-111111111111',
      'friend_request',
      '11111111-1111-4111-8111-111111111111',
      '44444444-4444-4444-8444-444444444444',
      1
    )
  $$,
  '%user_notifications_pair_version_key%',
  'the uniqueness constraint is the final notification idempotency safeguard'
);

-- Deterministic keyset pagination, bounded inputs, and duplicate-free pages.
delete from public.user_notifications;
delete from public.user_blocks;
delete from public.user_relationships;

insert into public.user_relationships (
  profile_low_id,
  profile_high_id,
  state,
  requester_id
)
select
  actor_id,
  '88888888-8888-4888-8888-888888888888'::uuid,
  'pending',
  actor_id
from (
  values
    ('11111111-1111-4111-8111-111111111111'::uuid),
    ('22222222-2222-4222-8222-222222222222'::uuid),
    ('33333333-3333-4333-8333-333333333333'::uuid),
    ('44444444-4444-4444-8444-444444444444'::uuid),
    ('55555555-5555-4555-8555-555555555555'::uuid)
) as actors(actor_id);

insert into public.user_notifications (
  id,
  recipient_id,
  actor_id,
  notification_type,
  relationship_low_id,
  relationship_high_id,
  relationship_version,
  created_at,
  expires_at
)
select
  notification_id,
  '88888888-8888-4888-8888-888888888888'::uuid,
  actor_id,
  'friend_request',
  actor_id,
  '88888888-8888-4888-8888-888888888888'::uuid,
  1,
  now() - age,
  now() - age + interval '180 days'
from (
  values
    ('00000000-0000-4000-8000-000000000001'::uuid, '11111111-1111-4111-8111-111111111111'::uuid, interval '1 minute'),
    ('00000000-0000-4000-8000-000000000002'::uuid, '22222222-2222-4222-8222-222222222222'::uuid, interval '2 minutes'),
    ('00000000-0000-4000-8000-000000000003'::uuid, '33333333-3333-4333-8333-333333333333'::uuid, interval '3 minutes'),
    ('00000000-0000-4000-8000-000000000004'::uuid, '44444444-4444-4444-8444-444444444444'::uuid, interval '4 minutes'),
    ('00000000-0000-4000-8000-000000000005'::uuid, '55555555-5555-4555-8555-555555555555'::uuid, interval '5 minutes')
) as fixtures(notification_id, actor_id, age);

set local role authenticated;
set local "request.jwt.claim.sub" = '88888888-8888-4888-8888-888888888888';

create temporary table notification_page_one as
select * from public.list_notifications(2, null, null);

select is(
  (
    select pg_catalog.array_agg(notification_id order by created_at desc, notification_id desc)
    from notification_page_one
  ),
  array[
    '00000000-0000-4000-8000-000000000001'::uuid,
    '00000000-0000-4000-8000-000000000002'::uuid
  ],
  'the first page is bounded and newest first'
);

create temporary table notification_page_two as
select *
from public.list_notifications(
  2,
  (select created_at from notification_page_one order by created_at, notification_id limit 1),
  (select notification_id from notification_page_one order by created_at, notification_id limit 1)
);

select is(
  (
    select pg_catalog.array_agg(notification_id order by created_at desc, notification_id desc)
    from notification_page_two
  ),
  array[
    '00000000-0000-4000-8000-000000000003'::uuid,
    '00000000-0000-4000-8000-000000000004'::uuid
  ],
  'the exclusive cursor returns the deterministic next page'
);

select ok(
  not exists (
    select notification_id from notification_page_one
    intersect
    select notification_id from notification_page_two
  ),
  'keyset pages contain no duplicates'
);

select is(
  (
    select count(*)
    from public.list_notifications(
      2,
      (select created_at from notification_page_two order by created_at, notification_id limit 1),
      (select notification_id from notification_page_two order by created_at, notification_id limit 1)
    )
  ),
  1::bigint,
  'the final keyset page contains the remaining row without skips'
);

select throws_ok(
  $$select * from public.list_notifications(0, null, null)$$,
  '22023',
  'invalid notification page size',
  'zero page size is rejected'
);

select throws_ok(
  $$select * from public.list_notifications(51, null, null)$$,
  '22023',
  'invalid notification page size',
  'page size above the server maximum is rejected'
);

select throws_ok(
  $$select * from public.list_notifications(20, now(), null)$$,
  '22023',
  'invalid notification cursor',
  'a cursor timestamp without an ID is rejected'
);

select throws_ok(
  $$select * from public.list_notifications(20, null, '00000000-0000-4000-8000-000000000001')$$,
  '22023',
  'invalid notification cursor',
  'a cursor ID without a timestamp is rejected'
);

-- Caller-owned bounded marking is idempotent and drives unread counts.
select is(
  public.get_unread_notification_count(),
  5::bigint,
  'the badge counts all five visible unread rows'
);

select lives_ok(
  $$select public.mark_notifications_read(array[]::uuid[])$$,
  'empty mark-read input is a safe no-op'
);

select is(
  public.get_unread_notification_count(),
  5::bigint,
  'empty marking leaves the unread count unchanged'
);

select lives_ok(
  $$
    select public.mark_notifications_read(array[
      '00000000-0000-4000-8000-000000000001'::uuid,
      '00000000-0000-4000-8000-000000000002'::uuid
    ])
  $$,
  'a displayed page can be marked read'
);

reset role;

select is(
  (
    select count(*)
    from public.user_notifications
    where read_at is not null
  ),
  2::bigint,
  'mark-read updates only the displayed caller-owned IDs'
);

reset role;

create temporary table read_timestamp_snapshot as
select id, read_at
from public.user_notifications
where read_at is not null;

set local role authenticated;
set local "request.jwt.claim.sub" = '88888888-8888-4888-8888-888888888888';

select lives_ok(
  $$
    select public.mark_notifications_read(array[
      '00000000-0000-4000-8000-000000000001'::uuid,
      '00000000-0000-4000-8000-000000000002'::uuid
    ])
  $$,
  'repeated mark-read is safe'
);

reset role;

select ok(
  not exists (
    select 1
    from public.user_notifications as current_row
    join read_timestamp_snapshot as snapshot using (id)
    where current_row.read_at <> snapshot.read_at
  ),
  'repeated mark-read preserves the original database timestamp'
);

insert into public.user_relationships (
  profile_low_id,
  profile_high_id,
  state,
  requester_id
)
values (
  '66666666-6666-4666-8666-666666666666',
  '77777777-7777-4777-8777-777777777777',
  'pending',
  '66666666-6666-4666-8666-666666666666'
);

insert into public.user_notifications (
  id,
  recipient_id,
  actor_id,
  notification_type,
  relationship_low_id,
  relationship_high_id,
  relationship_version
)
values (
  '00000000-0000-4000-8000-000000000099',
  '77777777-7777-4777-8777-777777777777',
  '66666666-6666-4666-8666-666666666666',
  'friend_request',
  '66666666-6666-4666-8666-666666666666',
  '77777777-7777-4777-8777-777777777777',
  1
);

set local role authenticated;
set local "request.jwt.claim.sub" = '88888888-8888-4888-8888-888888888888';

select lives_ok(
  $$select public.mark_notifications_read(array['00000000-0000-4000-8000-000000000099'::uuid])$$,
  'a cross-recipient ID is an enumeration-safe no-op'
);

reset role;

select ok(
  (
    select read_at is null
    from public.user_notifications
    where id = '00000000-0000-4000-8000-000000000099'
  ),
  'a caller cannot mark another recipient notification read'
);

set local role authenticated;
set local "request.jwt.claim.sub" = '88888888-8888-4888-8888-888888888888';

select throws_ok(
  $$
    select public.mark_notifications_read(
      pg_catalog.array_fill(
        '00000000-0000-4000-8000-000000000001'::uuid,
        array[51]
      )
    )
  $$,
  '22023',
  'invalid notification identifiers',
  'oversized mark-read input is rejected'
);

select throws_ok(
  $$select public.mark_notifications_read(null)$$,
  '22023',
  'invalid notification identifiers',
  'null mark-read input is rejected'
);

select throws_ok(
  $$select public.mark_notifications_read(array[null]::uuid[])$$,
  '22023',
  'invalid notification identifiers',
  'mark-read rejects null identifiers'
);

select is(
  public.get_unread_notification_count(),
  3::bigint,
  'the badge reflects successful caller-owned reads only'
);

-- Exact expiry, block-aware defense, permanent pair-wide suppression, and unblock.
reset role;

update public.user_notifications
set created_at = now() - interval '180 days',
    expires_at = now()
where id = '00000000-0000-4000-8000-000000000005';

set local role authenticated;
set local "request.jwt.claim.sub" = '88888888-8888-4888-8888-888888888888';

select is(
  (
    select count(*)
    from public.list_notifications(50, null, null)
    where notification_id = '00000000-0000-4000-8000-000000000005'
  ),
  0::bigint,
  'a notification is absent at the exact 180-day expiry boundary'
);

select is(
  public.get_unread_notification_count(),
  2::bigint,
  'the badge excludes an exactly expired unread notification'
);

select lives_ok(
  $$select public.mark_notifications_read(array['00000000-0000-4000-8000-000000000005'::uuid])$$,
  'marking an expired notification is a safe no-op'
);

reset role;

select ok(
  (
    select read_at is null
    from public.user_notifications
    where id = '00000000-0000-4000-8000-000000000005'
  ),
  'expired rows cannot be marked read'
);

insert into public.user_notifications (
  id,
  recipient_id,
  actor_id,
  notification_type,
  relationship_low_id,
  relationship_high_id,
  relationship_version
)
values (
  '00000000-0000-4000-8000-000000000103',
  '33333333-3333-4333-8333-333333333333',
  '88888888-8888-4888-8888-888888888888',
  'friend_request',
  '33333333-3333-4333-8333-333333333333',
  '88888888-8888-4888-8888-888888888888',
  2
);

set local role authenticated;
set local "request.jwt.claim.sub" = '88888888-8888-4888-8888-888888888888';

select lives_ok(
  $$select public.block_profile('33333333-3333-4333-8333-333333333333')$$,
  'block creation atomically deactivates the relationship and suppresses notifications'
);

reset role;

select is(
  (
    select count(*)
    from public.user_notifications
    where relationship_low_id = '33333333-3333-4333-8333-333333333333'
      and relationship_high_id = '88888888-8888-4888-8888-888888888888'
      and suppressed_at is not null
  ),
  2::bigint,
  'blocking permanently suppresses both notification recipient directions'
);

select ok(
  (
    select state = 'cancelled' and version = 2
    from public.user_relationships
    where profile_low_id = '33333333-3333-4333-8333-333333333333'
      and profile_high_id = '88888888-8888-4888-8888-888888888888'
  ),
  'the existing block relationship transition remains unchanged'
);

create temporary table suppression_timestamp_snapshot as
select id, suppressed_at
from public.user_notifications
where relationship_low_id = '33333333-3333-4333-8333-333333333333'
  and relationship_high_id = '88888888-8888-4888-8888-888888888888';

set local role authenticated;
set local "request.jwt.claim.sub" = '88888888-8888-4888-8888-888888888888';

select lives_ok(
  $$select public.block_profile('33333333-3333-4333-8333-333333333333')$$,
  'repeated block remains safe'
);

reset role;

select ok(
  not exists (
    select 1
    from public.user_notifications as current_row
    join suppression_timestamp_snapshot as snapshot using (id)
    where current_row.suppressed_at <> snapshot.suppressed_at
  ),
  'repeated block never rewrites an existing suppression timestamp'
);

set local role authenticated;
set local "request.jwt.claim.sub" = '88888888-8888-4888-8888-888888888888';

select is(
  (
    select count(*)
    from public.list_notifications(50, null, null)
    where actor_profile_id = '33333333-3333-4333-8333-333333333333'
  ),
  0::bigint,
  'suppressed pair notifications are absent from listing'
);

select lives_ok(
  $$select public.unblock_profile('33333333-3333-4333-8333-333333333333')$$,
  'the existing unblock RPC still removes only the caller block'
);

reset role;

select ok(
  not exists (
    select 1
    from public.user_blocks
    where blocker_id = '88888888-8888-4888-8888-888888888888'
      and blocked_id = '33333333-3333-4333-8333-333333333333'
  )
  and not exists (
    select 1
    from public.user_notifications
    where relationship_low_id = '33333333-3333-4333-8333-333333333333'
      and relationship_high_id = '88888888-8888-4888-8888-888888888888'
      and suppressed_at is null
  ),
  'unblocking never restores old notifications'
);

-- Privileged malformed writes prove every table constraint.
select throws_like(
  $$
    insert into public.user_notifications (
      recipient_id, actor_id, notification_type,
      relationship_low_id, relationship_high_id, relationship_version
    ) values (
      '11111111-1111-4111-8111-111111111111',
      '11111111-1111-4111-8111-111111111111',
      'friend_request',
      '11111111-1111-4111-8111-111111111111',
      '22222222-2222-4222-8222-222222222222',
      1
    )
  $$,
  '%user_notifications_distinct_participants_check%',
  'actor and recipient must differ'
);

select throws_like(
  $$
    insert into public.user_notifications (
      recipient_id, actor_id, notification_type,
      relationship_low_id, relationship_high_id, relationship_version
    ) values (
      '22222222-2222-4222-8222-222222222222',
      '11111111-1111-4111-8111-111111111111',
      'future_type',
      '11111111-1111-4111-8111-111111111111',
      '22222222-2222-4222-8222-222222222222',
      1
    )
  $$,
  '%user_notifications_type_check%',
  'unsupported notification types are rejected'
);

select throws_like(
  $$
    insert into public.user_notifications (
      recipient_id, actor_id, notification_type,
      relationship_low_id, relationship_high_id, relationship_version
    ) values (
      '77777777-7777-4777-8777-777777777777',
      '66666666-6666-4666-8666-666666666666',
      'friend_request',
      '66666666-6666-4666-8666-666666666666',
      '77777777-7777-4777-8777-777777777777',
      0
    )
  $$,
  '%user_notifications_positive_version_check%',
  'notification relationship versions must be positive'
);

select throws_like(
  $$
    insert into public.user_notifications (
      recipient_id, actor_id, notification_type,
      relationship_low_id, relationship_high_id, relationship_version,
      created_at, expires_at
    ) values (
      '77777777-7777-4777-8777-777777777777',
      '66666666-6666-4666-8666-666666666666',
      'friend_request',
      '66666666-6666-4666-8666-666666666666',
      '77777777-7777-4777-8777-777777777777',
      2,
      now(), now() + interval '179 days'
    )
  $$,
  '%user_notifications_exact_expiry_check%',
  'expiration must remain exactly 180 days after creation'
);

select throws_like(
  $$
    insert into public.user_notifications (
      recipient_id, actor_id, notification_type,
      relationship_low_id, relationship_high_id, relationship_version,
      created_at, expires_at, read_at
    ) values (
      '77777777-7777-4777-8777-777777777777',
      '66666666-6666-4666-8666-666666666666',
      'friend_request',
      '66666666-6666-4666-8666-666666666666',
      '77777777-7777-4777-8777-777777777777',
      2,
      now(), now() + interval '180 days', now() - interval '1 second'
    )
  $$,
  '%user_notifications_read_time_check%',
  'read time cannot precede creation'
);

select throws_like(
  $$
    insert into public.user_notifications (
      recipient_id, actor_id, notification_type,
      relationship_low_id, relationship_high_id, relationship_version,
      created_at, expires_at, suppressed_at
    ) values (
      '77777777-7777-4777-8777-777777777777',
      '66666666-6666-4666-8666-666666666666',
      'friend_request',
      '66666666-6666-4666-8666-666666666666',
      '77777777-7777-4777-8777-777777777777',
      2,
      now(), now() + interval '180 days', now() - interval '1 second'
    )
  $$,
  '%user_notifications_suppression_time_check%',
  'suppression time cannot precede creation'
);

select * from finish();
rollback;
